// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhgawyymlzqgqwarknkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZ2F3eXltbHpxZ3F3YXJrbmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTA5NzAsImV4cCI6MjA2MTg2Njk3MH0.YdA2mnrPVJXlQW755sZiPMd-gayKV86A2wW_c7QEsNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);